FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

# We'll mount the source code as a volume in docker-compose
# so we don't need to copy it here

EXPOSE 3000

CMD ["npm", "start"] 